Games = [
    ("Earwax", 3, 8, "Pack 2", False),
    ("Tee KO", 3, 8, "Pack 3", True),
    ("Fakin' it", 3, 6, "Pack 3", False),
    ("Survive the Internet", 3, 8, "Pack 4", False),
    ("Split the room", 3, 8, "Pack 5", False),
    ("Patently Stupid", 3, 8, "Pack 5", True),
    ("Trivia Murder Party", 1, 8, "Pack 6", False),
    ("Dictionarium", 3, 8, "Pack 6", False),
    ("Push the button", 4, 10, "Pack 6", False),
    ("Role Models", 3, 6, "Pack 6", False),
    ("Quiplash", 3, 8, "Pack 7", False),
    ("Blather round", 2, 6, "Pack 7", False),
    ("Champed up", 3, 8, "Pack 7", True),
    ("Devils in the details", 3, 8, "Pack 7", False),
    ("Talking Points", 2, 6, "Pack 7", False),
    ("Job Job", 3, 10, "Pack 8", False),
    ("Wheel of enormous proportions", 2, 8, "Pack 8", False),
    ("Poll mine", 2, 10, "Pack 8", False),
    ("Knives drawn", 4, 8, "Pack 8", True),
    ("Drawful animate", 3, 10, "Pack 8", True),
    ("Fibbage", 2, 8, "Pack 9", False),
    ("Quixort", 1, 10, "Pack 9", False), 
    ("Junktopia", 3, 8, "Pack 9", False),
    ("Non-Sensory", 3, 8, "Pack 9", True),
]